version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    entrypoint: ["java", "-jar", "-Dspring.profiles.active=dev", "/app.jar"]
    ports:
      - "8084:8080"

  db:
    image: postgres:alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testMogenius